const ASSETS={introIncoming:"M01a.png",introMission:"M01b.png",stationOnly:"MIa.png",dockedStation:"MIb.png",playerShip:"NVKeilan.png",map100:"MIc100.png",map60:"MIc60.png",map20:"MIc20.png"};
/* Coordenadas ajustadas a la nueva nave vertical. */
const ROOM_LAYOUT={
 A15:{x:12.4,y:17.6},A16:{x:75.2,y:17.6},
 B1:{x:12.4,y:26.1},A13:{x:28.1,y:26.1},A14:{x:59.6,y:26.1},B2:{x:75.2,y:26.1},
 A9:{x:12.4,y:34.7},A10:{x:28.1,y:34.7},B8:{x:43.8,y:34.7},A11:{x:59.6,y:34.7},A12:{x:75.2,y:34.7},
 B5:{x:28.1,y:43.3},B7:{x:59.6,y:43.3},
 B3:{x:12.4,y:51.9},A8:{x:28.1,y:51.9},B6:{x:43.8,y:51.9},A7:{x:59.6,y:51.9},B4:{x:75.2,y:51.9},
 A3:{x:12.4,y:60.4},A6:{x:28.1,y:60.4},A5:{x:59.6,y:60.4},A4:{x:75.2,y:60.4},
 A1:{x:12.4,y:69.0},A2:{x:75.2,y:69.0}
};
const GRAPH={
 ENTRADA:["B6","A6","A4"],
 A15:["B1"],B1:["A15","A9","A13"],A13:["B1"],A9:["B1","A10"],A10:["A9","B8","B5"],B8:["A10","A11"],B5:["A10","A8"],A8:["B5","B6","B3"],
 A16:["B2"],B2:["A16","A12","A14"],A14:["B2"],A12:["B2","A11"],A11:["A12","B8","B7"],B7:["A11","A7"],A7:["B7","B6","B4"],
 B6:["A8","A7"],B3:["A8","A3"],A3:["B3","A6","A1"],A6:["A3"],A1:["A3"],B4:["A7","A4"],A4:["B4","A5","A2"],A5:["A4"],A2:["A4"]
};
/* Los A con arte propio quedan fijos. El resto puede ser sala vacía. */
const FIXED_DEFINITIONS={
 A1:{type:"codeFinal",label:"PUERTA CERRADA",card:"A1E.png",finalCard:"SLV.png",icon:null},
 A2:{type:"codeFinal",label:"PUERTA CERRADA",card:"A2E.png",finalCard:"SLV.png",icon:null},
 A4:{type:"combat",label:"MARCIANO MORADO",card:"A4E.png",finalCard:"A4F.png",icon:"ICOMM.png",enemyColor:"purple",requiredLastHit:"gun",hp:{100:2,60:2,20:3}},
 A5:{type:"combat",label:"MARCIANO ROJO",card:"A5E.png",finalCard:"A5F.png",icon:"ICOMR.png",enemyColor:"red",requiredLastHit:"fist",hp:{100:3,60:4,20:4}},
 A6:{type:"combat",label:"MARCIANO VERDE",card:"A6E.png",finalCard:"A6F.png",icon:"ICOMV.png",enemyColor:"green",requiredLastHit:"fist",hp:{100:2,60:3,20:3}},
 A8:{type:"combat",label:"MARCIANO MORADO",card:"A8E.png",finalCard:"A8F.png",icon:"ICOMM.png",enemyColor:"purple",requiredLastHit:"gun",hp:{100:2,60:2,20:3}},
 A12:{type:"handshake",label:"SEÑAL BIOLÓGICA",card:"A12E.png",finalCard:"A12F.png",icon:"ICOMV.png"}
};
/* Conserva la mecánica de encuentros B aleatorios de la misión anterior, ahora con ocho salas. */
const B_EVENT_POOL=[
 {sourceId:"BT",type:"simple",label:"RECUPERAR VIDA",card:"SDV.png",icon:"ICOV.png"},
 {sourceId:"CO",type:"simple",label:"CAJA DE OBJETO",card:"CJO.png",icon:"ICOCO.png"},
 {sourceId:"TL",type:"simple",label:"TARJETA LLAVE",card:"TLL.png",icon:"ICOTL.png"},
 {sourceId:"TE",type:"simple",label:"TRAMPA DE ENERGÍA",card:"TRE.png",icon:"ICOTR.png"},
 {sourceId:"TV",type:"simple",label:"TRAMPA DE VIDA",card:"TRV.png",icon:"ICOTR.png"},
 {sourceId:"B6",type:"combat",label:"MARCIANO ROJO",card:"B6E.png",finalCard:"B6F.png",icon:"ICOMR.png",enemyColor:"red",requiredLastHit:"fist",hp:{100:3,60:4,20:4}},
 {sourceId:"B8",type:"combat",label:"MARCIANO VERDE",card:"B8E.png",finalCard:"B8F.png",icon:"ICOMV.png",enemyColor:"green",requiredLastHit:"fist",hp:{100:2,60:3,20:3}},
 {sourceId:"EMPTY",type:"empty",label:"SALA VACÍA",card:null,icon:null}
];
const DEFINITIONS={...FIXED_DEFINITIONS};
function randomIndex(max){if(window.crypto&&window.crypto.getRandomValues){const d=new Uint32Array(1);window.crypto.getRandomValues(d);return d[0]%max}return Math.floor(Math.random()*max)}
function shuffle(a){const r=[...a];for(let i=r.length-1;i>0;i--){const j=randomIndex(i+1);[r[i],r[j]]=[r[j],r[i]]}return r}
function randomizeB(){const rooms=["B1","B2","B3","B4","B5","B6","B7","B8"],draw=shuffle(B_EVENT_POOL);rooms.forEach((r,i)=>DEFINITIONS[r]=draw[i])}
randomizeB();
function definitionFor(room){return DEFINITIONS[room]||{type:"empty",label:"SALA VACÍA",card:null,icon:null}}
const state={currentRoom:"ENTRADA",oxygen:100,scannerActive:false,pendingRoom:null,encounterMode:null,combat:null,gameLocked:true,ended:false,rooms:{}};Object.keys(ROOM_LAYOUT).forEach(r=>state.rooms[r]={revealed:false,completed:false,visited:false});
const $=id=>document.getElementById(id),introOverlay=$("introOverlay"),introPage1=$("introPage1"),introPage2=$("introPage2"),dockPage=$("dockPage"),acceptMissionButton=$("acceptMissionButton"),dockBaseImage=$("dockBaseImage"),dockShip=$("dockShip"),dockFlash=$("dockFlash"),game=$("game"),mapImage=$("mapImage"),roomsLayer=$("roomsLayer"),iconsLayer=$("iconsLayer"),scannerButton=$("scannerButton"),useObjectButton=$("useObjectButton"),musicButton=$("musicButton"),oxygenCounter=$("oxygenCounter"),tutorialOverlay=$("tutorialOverlay"),tutorialText=$("tutorialText"),tutorialNext=$("tutorialNext"),encounter=$("encounter"),encounterCard=$("encounterCard"),encounterImage=$("encounterImage"),enemyHp=$("enemyHp"),gunButton=$("gunButton"),fistButton=$("fistButton"),handshakeButton=$("handshakeButton"),codePanel=$("codePanel"),doorCode=$("doorCode"),submitCode=$("submitCode"),encounterBackButton=$("encounterBackButton"),message=$("message"),endOverlay=$("endOverlay"),endTitle=$("endTitle"),endSubtitle=$("endSubtitle"),introMusic=$("introMusic"),bgMusic=$("bgMusic");
let messageTimer=null,musicPlaying=false,combatLocked=false,introLocked=false,audioCtx=null,tutorialIndex=0;introMusic.volume=.34;bgMusic.volume=.32;
function buildRooms(){Object.entries(ROOM_LAYOUT).forEach(([r,p])=>{const b=document.createElement("button");b.type="button";b.className="room";b.id=`room-${r}`;b.setAttribute("aria-label",`Habitación ${r}`);b.style.left=`${p.x}%`;b.style.top=`${p.y}%`;b.style.width="14.5%";b.style.height="8.0%";b.addEventListener("click",()=>handleRoomClick(r));roomsLayer.appendChild(b)})}buildRooms();
const preload=[...Object.values(ASSETS)];Object.values(DEFINITIONS).forEach(d=>{[d.card,d.finalCard,d.icon].filter(Boolean).forEach(x=>preload.push(x))});preload.filter(Boolean).forEach(src=>{const i=new Image();i.src=src});
function getAudioContext(){try{if(!audioCtx){const C=window.AudioContext||window.webkitAudioContext;audioCtx=new C()}if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}catch(e){return null}}
function toneSweep(a,b,d,v=.1,t="sine"){try{const c=getAudioContext();if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.setValueAtTime(a,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,b),c.currentTime+d);g.gain.setValueAtTime(v,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+d+.02)}catch(e){}}
function scannerSound(){toneSweep(380,1240,.48,.085,"sine")}function punchSound(){toneSweep(165,48,.17,.32,"triangle")}function lifeLossSound(){[270,195,128].forEach((f,i)=>setTimeout(()=>toneSweep(f,f*.92,.11,.07,"square"),i*60))}function gunSound(){toneSweep(1250,170,.15,.2,"sawtooth")}function energyLossSound(){toneSweep(720,180,.33,.11,"sine")}function itemSound(){toneSweep(520,900,.24,.08,"triangle")}function deathSound(){[430,300,180,95].forEach((f,i)=>setTimeout(()=>toneSweep(f,Math.max(45,f*.55),.2,.11,i<2?"square":"sawtooth"),i*85))}function gameOverSound(){toneSweep(240,45,1.1,.18,"sawtooth")}function missionSound(){[520,690,880,1180].forEach((f,i)=>setTimeout(()=>toneSweep(f,f*1.02,.22,.08,"sine"),i*120))}function dockingTravelSound(){toneSweep(58,98,2.25,.09,"sawtooth")}function dockingImpactSound(){toneSweep(115,42,.25,.24,"square");setTimeout(()=>toneSweep(610,610,.11,.08,"sine"),170);setTimeout(()=>toneSweep(830,830,.11,.08,"sine"),270)}
function showIntroPage(p){[introPage1,introPage2,dockPage].forEach(x=>x.classList.remove("active"));p.classList.add("active")}
introPage1.addEventListener("click",async()=>{if(introLocked)return;getAudioContext();showIntroPage(introPage2);try{introMusic.currentTime=0;await introMusic.play()}catch(e){}});
function crossfadeToGameMusic(){bgMusic.volume=.03;bgMusic.play().then(()=>{musicPlaying=true;musicButton.classList.add("music-on")}).catch(()=>{});let current=0;const steps=18,start=introMusic.volume,t=setInterval(()=>{current++;const p=current/steps;introMusic.volume=Math.max(0,start*(1-p));bgMusic.volume=.03+(.32-.03)*p;if(current>=steps){clearInterval(t);introMusic.pause();introMusic.currentTime=0;introMusic.volume=.34;bgMusic.volume=.32}},65)}
acceptMissionButton.addEventListener("click",e=>{e.stopPropagation();if(introLocked)return;introLocked=true;getAudioContext();crossfadeToGameMusic();dockingTravelSound();startDockingSequence()});
function startDockingSequence(){showIntroPage(dockPage);dockBaseImage.src=ASSETS.stationOnly;dockShip.src=ASSETS.playerShip;dockShip.style.display="block";dockShip.classList.remove("docking");void dockShip.offsetWidth;setTimeout(()=>dockShip.classList.add("docking"),180);setTimeout(()=>{dockingImpactSound();dockFlash.classList.remove("flash");void dockFlash.offsetWidth;dockFlash.classList.add("flash");dockBaseImage.src=ASSETS.dockedStation;dockShip.style.display="none"},2450);setTimeout(startGame,3150)}
function startGame(){mapImage.src=ASSETS.map100;state.oxygen=100;updateOxygenUI();introOverlay.style.display="none";game.style.display="block";window.scrollTo(0,0);refreshRoomMarkers();showTutorial()}
async function toggleMusic(){if(!musicPlaying){try{await bgMusic.play();musicPlaying=true;musicButton.classList.add("music-on")}catch(e){showMessage("NO SE PUDO ACTIVAR LA MÚSICA")}return}bgMusic.pause();musicPlaying=false;musicButton.classList.remove("music-on")}musicButton.addEventListener("click",e=>{e.stopPropagation();toggleMusic()});
const TUTORIAL_MESSAGES=["Recuerda: tu oxígeno es limitado. Cuanto menos te quede, más difícil será combatir. Úsalo con prudencia.","No olvides llevar tu Intergalactic Purée y una batería de reserva.","Si necesitas usar un objeto da clic en USAR OBJETO."];function showTutorial(){state.gameLocked=true;tutorialIndex=0;tutorialText.textContent=TUTORIAL_MESSAGES[0];tutorialNext.textContent="SIGUIENTE";tutorialOverlay.classList.add("show")}tutorialNext.addEventListener("click",()=>{tutorialIndex++;if(tutorialIndex>=TUTORIAL_MESSAGES.length){tutorialOverlay.classList.remove("show");state.gameLocked=false;return}tutorialText.textContent=TUTORIAL_MESSAGES[tutorialIndex];tutorialNext.textContent=tutorialIndex===TUTORIAL_MESSAGES.length-1?"ENTENDIDO":"SIGUIENTE"});
function showMessage(html){clearTimeout(messageTimer);message.classList.remove("show");void message.offsetWidth;message.innerHTML=html;message.classList.add("show");messageTimer=setTimeout(()=>message.classList.remove("show"),1400)}
function oxygenPhase(){if(state.oxygen<20)return 20;if(state.oxygen<60)return 60;return 100}function formatOxygen(v){return `${Number.isInteger(v)?v:v.toFixed(1).replace(".",",")}%`}function updateOxygenUI(){const p=oxygenPhase();oxygenCounter.textContent=formatOxygen(state.oxygen);oxygenCounter.classList.remove("phase60","phase20");mapImage.src=p===100?ASSETS.map100:p===60?ASSETS.map60:ASSETS.map20;if(p===60)oxygenCounter.classList.add("phase60");if(p===20)oxygenCounter.classList.add("phase20")}function consumeOxygen(a){if(state.ended)return false;state.oxygen=Math.max(0,Math.round((state.oxygen-a)*10)/10);updateOxygenUI();if(state.oxygen<=0){triggerGameOver();return false}return true}function getMovementOxygenCost(target){if(state.currentRoom==="ENTRADA")return 0;if(state.rooms[target]&&state.rooms[target].visited)return 2.5;return 5}
useObjectButton.addEventListener("click",()=>{if(state.gameLocked||state.ended||encounter.classList.contains("show"))return;itemSound();if(consumeOxygen(5))showMessage("OBJETO UTILIZADO<br>−5% O₂")});
function marker(id,room,cls,text=""){removeMarker(id);const p=ROOM_LAYOUT[room];if(!p)return;const el=document.createElement("div");el.id=id;el.className=cls;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.textContent=text;iconsLayer.appendChild(el);return el}function imageMarker(id,room,src){removeMarker(id);const p=ROOM_LAYOUT[room];if(!p||!src)return;const el=document.createElement("img");el.id=id;el.className="map-icon event-icon";el.src=src;el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;iconsLayer.appendChild(el);return el}function removeMarker(id){const e=$(id);if(e)e.remove()}function clearMarkers(){removeMarker("player-marker");Object.keys(ROOM_LAYOUT).forEach(r=>{removeMarker(`check-${r}`);removeMarker(`event-${r}`)})}
function refreshRoomMarkers(){clearMarkers();if(state.currentRoom!=="ENTRADA")marker("player-marker",state.currentRoom,"player-marker","K");Object.keys(ROOM_LAYOUT).forEach(r=>{const s=state.rooms[r],d=definitionFor(r);if(r===state.currentRoom)return;if(s.completed){marker(`check-${r}`,r,"check-marker","✓");return}if(s.revealed&&d.icon&&d.type!=="empty")imageMarker(`event-${r}`,r,d.icon)})}
function moveToRoom(r){state.currentRoom=r;state.rooms[r].visited=true;refreshRoomMarkers()}
function adjacentRooms(){return GRAPH[state.currentRoom]||[]}function isAdjacent(r){return adjacentRooms().includes(r)}function directionBetween(from,to){if(from==="ENTRADA"){if(to==="B6")return"up";if(to==="A6")return"left";return"right"}const a=ROOM_LAYOUT[from],b=ROOM_LAYOUT[to];if(!a||!b)return"up";const dx=b.x-a.x,dy=b.y-a.y;return Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"down":"up")}
function turnOffScanner(){state.scannerActive=false;scannerButton.classList.remove("scanner-on");Object.keys(ROOM_LAYOUT).forEach(r=>removeMarker(`scan-${r}`))}function scanNearbyRooms(){if(state.gameLocked||state.ended||encounter.classList.contains("show"))return;if(state.scannerActive){turnOffScanner();return}let count=0;adjacentRooms().forEach(r=>{const s=state.rooms[r];if(!s.completed&&!s.revealed){const m=marker(`scan-${r}`,r,`scan-marker dir-${directionBetween(state.currentRoom,r)}`,"⌃");if(m)count++}});if(!count){showMessage("SIN NUEVAS SEÑALES");return}state.scannerActive=true;scannerButton.classList.add("scanner-on");scannerSound()}scannerButton.addEventListener("click",scanNearbyRooms);
function revealRoom(r){const s=state.rooms[r],d=definitionFor(r);if(!s)return;s.revealed=true;removeMarker(`scan-${r}`);if(d.icon&&d.type!=="empty")imageMarker(`event-${r}`,r,d.icon);energyLossSound();showMessage(`${d.label}<br>−2 ENERGÍAS`)}
function setEncounterImage(src){encounterImage.onerror=null;encounterImage.src=src||""}function resetEncounterUI(){encounterCard.className="";encounterCard.style.cursor="default";enemyHp.style.display="none";gunButton.style.display="none";fistButton.style.display="none";handshakeButton.style.display="none";encounterBackButton.style.display="none";codePanel.classList.remove("show");doorCode.value="";combatLocked=false;state.combat=null}
function currentEnemyHp(d){return d.hp?d.hp[oxygenPhase()]:0}
function openEncounter(r){const d=definitionFor(r);turnOffScanner();state.pendingRoom=r;state.rooms[r].visited=true;if(d.type==="empty"){state.rooms[r].revealed=true;state.rooms[r].completed=true;moveToRoom(r);showMessage("SALA VACÍA");return}resetEncounterUI();setEncounterImage(d.card);encounterImage.alt=d.label;encounter.classList.add("show");state.encounterMode=d.type;if(d.type==="combat"){encounterCard.classList.add("combat");enemyHp.style.display="flex";gunButton.style.display="block";fistButton.style.display="block";const hp=currentEnemyHp(d);state.combat={room:r,sourceId:d.sourceId||r,hp,lastHit:null};enemyHp.textContent=hp;return}if(d.type==="codeFinal"){codePanel.classList.add("show");encounterBackButton.style.display="block";setTimeout(()=>doorCode.focus(),200);return}if(d.type==="handshake"){encounterCard.classList.add("handshake");handshakeButton.style.display="block";encounterBackButton.style.display="block";return}encounterCard.style.cursor="pointer"}
function completeCurrentRoom(){const r=state.pendingRoom;if(!r)return;state.rooms[r].completed=true;state.rooms[r].revealed=true;encounter.classList.remove("show");state.pendingRoom=null;state.encounterMode=null;resetEncounterUI();moveToRoom(r)}function closeUnresolvedToMap(){const r=state.pendingRoom;if(!r)return;state.rooms[r].revealed=true;encounter.classList.remove("show");state.pendingRoom=null;state.encounterMode=null;resetEncounterUI();moveToRoom(r)}function animateHit(){encounterCard.classList.remove("hit");void encounterCard.offsetWidth;encounterCard.classList.add("hit")}
function attack(kind){if(state.encounterMode!=="combat"||combatLocked||!state.combat||state.ended)return;combatLocked=true;const c=state.combat;c.lastHit=kind;if(kind==="fist"){punchSound();setTimeout(lifeLossSound,65);showMessage("−1 VIDA")}else{gunSound();setTimeout(energyLossSound,65);showMessage("−1 ENERGÍA")}c.hp=Math.max(0,c.hp-1);enemyHp.textContent=c.hp;animateHit();setTimeout(()=>{if(c.hp>0){combatLocked=false;return}const d=definitionFor(c.room),earnsClue=c.lastHit===d.requiredLastHit&&!!d.finalCard;if(earnsClue){state.encounterMode="final";encounterCard.classList.remove("combat");enemyHp.style.display="none";gunButton.style.display="none";fistButton.style.display="none";setEncounterImage(d.finalCard);encounterCard.style.cursor="pointer";combatLocked=false;return}deathSound();setTimeout(completeCurrentRoom,430)},320)}
gunButton.addEventListener("click",e=>{e.stopPropagation();attack("gun")});fistButton.addEventListener("click",e=>{e.stopPropagation();attack("fist")});
handshakeButton.addEventListener("click",e=>{e.stopPropagation();if(state.encounterMode!=="handshake"||state.pendingRoom!=="A12")return;const d=definitionFor("A12");state.encounterMode="handshakeFinal";encounterCard.classList.remove("handshake");handshakeButton.style.display="none";encounterBackButton.style.display="none";setEncounterImage(d.finalCard);encounterCard.style.cursor="pointer";itemSound()});
function submitDoorCode(){if(state.encounterMode!=="codeFinal")return;if(doorCode.value.trim()!=="3435"){showMessage("CÓDIGO INCORRECTO");doorCode.select();return}const r=state.pendingRoom,d=definitionFor(r);state.encounterMode="missionFinal";codePanel.classList.remove("show");encounterBackButton.style.display="none";setEncounterImage(d.finalCard);encounterCard.style.cursor="pointer";dockingImpactSound()}submitCode.addEventListener("click",e=>{e.stopPropagation();submitDoorCode()});doorCode.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();submitDoorCode()}});doorCode.addEventListener("input",()=>{doorCode.value=doorCode.value.replace(/\D/g,"").slice(0,4)});
encounterBackButton.addEventListener("click",e=>{e.stopPropagation();if(["codeFinal","handshake"].includes(state.encounterMode))closeUnresolvedToMap()});
encounterCard.addEventListener("click",()=>{if(state.encounterMode==="simple"||state.encounterMode==="final"||state.encounterMode==="handshakeFinal"){completeCurrentRoom();return}if(state.encounterMode==="missionFinal"){const r=state.pendingRoom;if(r){state.rooms[r].completed=true;state.rooms[r].revealed=true}missionComplete()}});
function handleRoomClick(r){if(state.gameLocked||state.ended||encounter.classList.contains("show"))return;if(r===state.currentRoom){showMessage("ESTÁS EN ESTA SALA");return}if(!isAdjacent(r)){showMessage("SOLO PUEDES IR A UNA SALA ALEDAÑA");return}if(state.scannerActive&&!state.rooms[r].revealed){revealRoom(r);return}const cost=getMovementOxygenCost(r);if(cost>0&&!consumeOxygen(cost))return;if(state.rooms[r].completed){turnOffScanner();moveToRoom(r);return}openEncounter(r)}
function triggerGameOver(){if(state.ended)return;state.ended=true;state.gameLocked=true;turnOffScanner();encounter.classList.remove("show");gameOverSound();endOverlay.className="show gameover";endTitle.textContent="GAME OVER";endSubtitle.textContent="Te has quedado sin oxígeno."}function missionComplete(){if(state.ended)return;state.ended=true;state.gameLocked=true;turnOffScanner();encounter.classList.remove("show");missionSound();endOverlay.className="show mission";endTitle.textContent="MISIÓN CUMPLIDA";endSubtitle.textContent="Has descubierto lo que ocultaban los marcianos."}
let lastTouchEnd=0;document.addEventListener("touchend",e=>{const now=Date.now();if(now-lastTouchEnd<=300)e.preventDefault();lastTouchEnd=now},{passive:false});
